version: '2'
services:
    back:
        build:
            context: ./back/
        command: npm start
        volumes:
            - ./back/:/usr/back
        ports:
            - "8080:8080"
        env_file: ./.env
        links:
            - database
    database:
        image: mongo
        ports:
            - "27017:27017"
    front:
        build:
            context: ./front/
        command: npm start
        volumes:
            - ./front/:/app
        ports:
            - "4200:4200"
        env_file: ./.env
